<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>@yield('title')</title>
<style>
*{box-sizing:border-box}body{margin:0;font:16px/1.55 Arial,sans-serif;color:#172433;background:#fff}header{border-bottom:1px solid #d8e0e8;padding:18px 6%;display:flex;justify-content:space-between;align-items:center;gap:20px}header a{color:#243b53;text-decoration:none;margin-right:18px}.brand{font-weight:700;font-size:21px}main{max-width:1100px;margin:44px auto;padding:0 24px}h1{font-size:32px;line-height:1.2;margin:0 0 20px}h2{font-size:23px}p{max-width:800px}.actions{display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin:20px 0}.button,button{display:inline-block;background:#165d48;color:white;border:0;border-radius:4px;padding:10px 17px;font:600 15px Arial;cursor:pointer;text-decoration:none}a{color:#125d79}.secondary{background:#e7eef4;color:#243b53}.danger{background:#a32d39}label{display:block;font-weight:600;margin:18px 0 6px}input,select,textarea{width:100%;max-width:650px;padding:11px;border:1px solid #9caebd;border-radius:4px;font:16px Arial}textarea{min-height:120px}.notice{background:#e9f6ee;padding:12px 16px;margin-bottom:20px}.errors{background:#fff0f0;padding:12px;color:#8c1b28}table{border-collapse:collapse;width:100%;margin-top:22px}th,td{text-align:left;padding:13px 12px;border-bottom:1px solid #d8e0e8;vertical-align:middle}th{background:#f0f4f7;font-size:14px}td form{display:inline-block}td button{padding:7px 11px}td a{margin-right:10px}.portrait{width:80px;height:80px;object-fit:cover;border-radius:5px}.detail-photo{max-width:280px;max-height:300px;border-radius:5px}small{color:#506579}footer{max-width:1100px;margin:65px auto 20px;padding:0 24px;color:#617488;font-size:13px}.table-wrap{overflow-x:auto}.form{max-width:700px}@media(max-width:650px){header{padding:15px 20px;flex-wrap:wrap}main{margin-top:28px}h1{font-size:27px}th,td{padding:10px 8px}.portrait{width:50px;height:50px}}
</style></head><body><header><a class="brand" href="/">{{ config('app.name') }}</a><nav>@yield('nav')</nav></header><main>
@if(session('status'))<div class="notice" role="status">{{ session('status') }}</div>@endif
@if($errors->any())<div class="errors" role="alert"><strong>Revisa los datos</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@yield('content')</main><footer>Aplicaciones web · Módulo 2</footer></body></html>

